services:

  espocrm-db:
    image: mariadb:latest
    container_name: nexuscrm_db
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-espocrm}
      MARIADB_USER: ${MARIADB_USER:-espocrm}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

    volumes:
      - espocrm_db:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  espocrm:
    image: espocrm/espocrm:latest
    container_name: nexuscrm_espocrm
    restart: unless-stopped

    environment:
      ESPOCRM_DATABASE_PLATFORM: Mysql
      ESPOCRM_DATABASE_HOST: ${ESPOCRM_DATABASE_HOST:-espocrm-db}
      ESPOCRM_DATABASE_PORT: ${ESPOCRM_DATABASE_PORT:-3306}
      ESPOCRM_DATABASE_NAME: ${ESPOCRM_DATABASE_NAME:-espocrm}
      ESPOCRM_DATABASE_USER: ${ESPOCRM_DATABASE_USER:-espocrm}
      ESPOCRM_DATABASE_PASSWORD: ${ESPOCRM_DATABASE_PASSWORD}

      ESPOCRM_ADMIN_USERNAME: ${ESPOCRM_ADMIN_USERNAME:-admin}
      ESPOCRM_ADMIN_PASSWORD: ${ESPOCRM_ADMIN_PASSWORD}

      ESPOCRM_SITE_URL: ${ESPOCRM_SITE_URL:-http://localhost:8080}

    depends_on:
      espocrm-db:
        condition: service_healthy

    volumes:
      - espocrm_data:/var/www/html/data
      - espocrm_custom:/var/www/html/custom
      - espocrm_custom_client:/var/www/html/client/custom

    ports:
      - "8080:80"

  espocrm-daemon:
    image: espocrm/espocrm:latest
    container_name: nexuscrm_daemon
    restart: unless-stopped

    volumes:
      - espocrm_data:/var/www/html/data
      - espocrm_custom:/var/www/html/custom
      - espocrm_custom_client:/var/www/html/client/custom

    depends_on:
      - espocrm

    entrypoint: docker-daemon.sh

volumes:
  espocrm_db:
  espocrm_data:
  espocrm_custom:
  espocrm_custom_client:
